spring:
   cloud:
      stream:
         bindings:
            user:
               group: searchService
               destination: user
               consumer:
                  max-attempts: 1
                  back-off-initial-interval: 100
                  default-retryable: false
                  concurrency: 1
                  valueSerde: "org.springframework.kafka.support.serializer.JsonSerde"
                  keySerde: "org.springframework.kafka.support.serializer.StringSerde"
            user_output:
               destination: user
               producer:
                  valueSerde: "org.springframework.kafka.support.serializer.JsonSerde"
                  keySerde: "org.springframework.kafka.support.serializer.StringSerde"
                  key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
                  retries: 3
                  acks: 1
         kafka:
            binder:
               brokers: localhost:9092
               auto-add-partitions: true
               auto-create-topics: true
               consumer-properties:
                  key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value.serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
               producer-properties:
                  key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value.serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
            bindings:
               user:
                  producer:
                     useNativeEncoding: true
                     key:
                        serializer: "org.apache.kafka.common.serialization.StringSerializer"
                     value:
                        serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
                     retries: 3
                     acks: 1
                     topic:
                        properties:
                           message:
                              format:
                                 version: 0.9.0.0
                  consumer:
                     enable-dlq: true
                     dlq-name: "user.errors"
                     dlq-partitions: 1

logging:
   level:
      root: ERROR
      org:
         springframework:
            web: ERROR
      io:
         thepro: ERROR
   pattern:
      console: "%d{HH:mm:ss} || %highlight(%5p) < %highlight(%-35.35logger{35}) > %highlight(%m%n)"
    