security:
   cookie-props:
      max-age-in-minutes: 7200
      http-only: true
      secure: true
      domain: eduserve.co.in
      path: /
   allow-credentials: true
   allowed-origins:
   - http://localhost:8080
   allowed-methods:
   - GET
   - POST
   - PUT
   - PATCH
   - DELETE
   - OPTIONS
   allowed-headers:
   - Authorization
   - Origin
   - Content-Type
   - Accept
   - Accept-Encoding
   - Accept-Language
   - Access-Control-Allow-Origin
   - Access-Control-Allow-Headers
   - Access-Control-Request-Method
   - X-Requested-With
   - X-Auth-Token
   - X-Xsrf-Token
   - Cache-Control
   - Id-Token
   allowed-public-apis:
   - /favicon.ico
   - /user/**
   - /search/**
   - /index/**
   - /test/**
   exposed-headers:
   - X-Xsrf-Token
   - Access-Control-Allow-Origin
   valid-application-roles:
   - ROLE_ADMIN
   - ROLE_CUSTOMER
   super-admins:

   test:
      login:
         enabled: ${TEST_LOGIN_ENABLED}

spring:
   cloud:
      stream:
         bindings:
            user:
               group: searchService
               destination: user
               consumer:
                  max-attempts: 1
                  back-off-initial-interval: 100
                  default-retryable: false
                  concurrency: 1
                  valueSerde: "org.springframework.kafka.support.serializer.JsonSerde"
                  keySerde: "org.springframework.kafka.support.serializer.StringSerde"
            user_output:
               destination: user
               producer:
                  valueSerde: "org.springframework.kafka.support.serializer.JsonSerde"
                  keySerde: "org.springframework.kafka.support.serializer.StringSerde"
                  key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
                  retries: 3
                  acks: 1
         kafka:
            binder:
               brokers: localhost:9092
               auto-add-partitions: true
               auto-create-topics: true
               consumer-properties:
                  key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value.serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
               producer-properties:
                  key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                  value.serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
            bindings:
               user:
                  producer:
                     useNativeEncoding: true
                     key:
                        serializer: "org.apache.kafka.common.serialization.StringSerializer"
                     value:
                        serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
                     retries: 3
                     acks: 1
                     topic:
                        properties:
                           message:
                              format:
                                 version: 0.9.0.0
                  consumer:
                     enable-dlq: true
                     dlq-name: "user.errors"
                     dlq-partitions: 1

logging:
   level:
      root: ERROR
      org:
         springframework:
            web: ERROR
      io:
         thepro: ERROR
   pattern:
      console: "%d{HH:mm:ss} || %highlight(%5p) < %highlight(%-35.35logger{35}) > %highlight(%m%n)"
    